load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "async_commit_example",
    srcs = glob([
        "*.java",
        "async_commit_example/*.java",
        "async_commit_example/annotations/*.java",
    ]),
    deps = [
    ],
)

